# Modern pre-commit configuration using ruff and uv
exclude: ^(venv/|\.venv/|env/|\.env/|build/|dist/|\.tox/|\.eggs/|.*\.egg-info/|__pycache__/|coverage/|\.coverage.*|\.mypy_cache/|\.pytest_cache/|node_modules/)

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=25600']  # 25MB limit
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-docstring-first

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml]
        additional_dependencies: [
          "types-requests",
          "pandas-stubs",
          "types-setuptools",
          "pytest",
          "numpy",
          "pandas",
          "scikit-learn"
        ]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.0
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
