site_name: YAAML - Yet Another AutoML
site_description: A native Python AutoML library with comprehensive preprocessing
site_author: Varun Rajan
site_url: https://jordanrex.github.io/yaaml

repo_name: JordanRex/yaaml
repo_url: https://github.com/JordanRex/yaaml

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_category_heading: true
            merge_init_into_class: true
            separate_signature: true

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide:
    - Installation: user-guide/installation.md
    - Quick Start: user-guide/quickstart.md
    - AutoML Pipeline: user-guide/pipeline.md
    - Examples: user-guide/examples.md
  - API Reference:
    - Core: api/core.md
    - Preprocessing: api/preprocessing.md
    - Models: api/models.md
  - Development:
    - Contributing: development/contributing.md
    - Testing: development/testing.md
    - Release Process: development/release.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
